FROM node:16-buster

ARG port=2999
WORKDIR /app
COPY ./package.json /app/

RUN npm install

COPY . /app/

EXPOSE $port

# Command can be overwritten by providing a different command in the template directly.
CMD ["node", "dist/reader/index.js"]