version: "3.9"
services:
  reader:
    build:
      context: .
      dockerfile: Dockerfile.reader
    ports:
      - "2999:2999"
    depends_on:
      - redis
      - writer
  writer:
    build:
      context: .
      dockerfile: Dockerfile.writer
    ports:
      - "3001:3001"
    depends_on:
      - redis
  redis:
    image: "redis"
    ports:
      - "6379:6379"
