AWSTemplateFormatVersion: '2010-09-09'

Resources:

  # Writer related
  ECSVPCRole:
    Type: AWS::IAM::Role
    Properties:
      Description: "Allows ECS tasks to call AWS services on your behalf."
      MaxSessionDuration: 3600
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonECS_FullAccess"
      RoleName: "ecs-vpc-role"
  RPCCacheWriterContainerTask:
    Type: AWS::ECS::TaskDefinition
    Memory: "2048"
    Cpu: "1024"
    NetworkMode: "awsvpc"
    
  # Cache related
  RPCCache:
    Type: AWS::ElastiCache::CacheCluster
    Properties: 
      AutoMinorVersionUpgrade: yes
      CacheNodeType: "cache.t2.small" 
      CacheSubnetGroupName: String
      ClusterName: String
      Engine: "redis"
      EngineVersion: "6.0.5"
      NumCacheNodes: 2
  
